import Sidebar from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MusicControls from "@/components/MusicControls";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} p-2 grid grid-cols-[auto_1fr] grid-rows-[1fr_auto] gap-2 main-layout h-full min-h-screen `}
      >
        <Sidebar />
        {children}
        <MusicControls />
      </body>
    </html>
  );
}
